### PR TITLE
add memberof and refint overlays

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This PR adds the [Reverse Group Membership (`memberof`)](http://www.openldap.org/doc/admin24/overlays.html#Reverse%20Group%20Membership%20Maintenance) and [Referential Integrity (`refint`)](http://www.openldap.org/doc/admin24/overlays.html#Referential%20Integrity) overlays to the OpenLDAP image. These overlays enable us to use a Active-Directory-esque `memberOf` query that exposes reverse membership data without storing it in explicit attributes on our user entries.

The `ldif` to load the modules is found in [`load_modules.ldif`](https://github.com/openshift/openldap/pull/10/files#diff-e2d0ef3a266720e4dfdf8a4daa191486).
The `ldif` to configure the `memberof` overlay is found in [`configure_memberof.ldif`](https://github.com/openshift/openldap/pull/10/files#diff-dd1a97da0e8d24390fecd4b67345f8c3).
The `ldif` to configure the `refint` overlay is found in [`configure_refint.ldif`](https://github.com/openshift/openldap/pull/10/files#diff-2c5a997d08c11a4c0830e0613b6f61ad).

The server is configured [here](https://github.com/openshift/openldap/pull/10/files#diff-eecfd099a4e70f906748c95b07c290a0R55).

@liggitt @deads2k PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
why are tons of files now executable?

**Comment by stevekuznetsov** [comment]
Change should have been to `chmod a+rw` the necessary files. I'll look into it tomorrow.

**Comment by deads2k** [comment]
I don't see this as working.  Please take it through the whole flow, including your ldif file from https://github.com/openshift/origin/pull/4923 and a search `ldapsearch -h 172.30.216.211:389 -x -b "ou=ad,dc=example,dc=com"` to confirm that you get back all the groups.

**Comment by stevekuznetsov** [comment]
@deads2k You are correct in noticing that the current version of the `ldif` in https://github.com/openshift/origin/pull/4923 is not valid. We cannot specify `memberOf` attributes as they do not actually exist on the server as attributes and are instead calculated at query-time. That's a separate issue and easy to solve. We also cannot have a pure Active-Directory schema in OpenLDAP - first-class groups must always exist. However, the Active Directory syncer will work fine with enhanced Active Directory schemas, with the downside of not being able to grab metadata. Here's output I get by adding the _current_ version of the `ldif`:

``` sh
$ docker run -u 1001 openshift/openldap-2441-centos7
$ docker exec -it b9dd8d67e72d bash
$ ldapadd -x -D cn=Manager,dc=example,dc=com -w admin -f init.ldif #with init.ldif from HEAD of origin
adding new entry "ou=groups,dc=example,dc=com"
adding new entry "ou=people,dc=example,dc=com"
adding new entry "cn=Person1,ou=people,dc=example,dc=com"
adding new entry "cn=Person2,ou=people,dc=example,dc=com"
adding new entry "cn=Person3,ou=people,dc=example,dc=com"
adding new entry "cn=Person4,ou=people,dc=example,dc=com"
adding new entry "cn=Person5,ou=people,dc=example,dc=com"
adding new entry "cn=group1,ou=groups,dc=example,dc=com"
adding new entry "cn=group2,ou=groups,dc=example,dc=com"
adding new entry "cn=group3,ou=groups,dc=example,dc=com"
$ ldapsearch -LLL -x -b cn=Person1,ou=people,dc=example,dc=com dn memberof
dn: cn=Person1,ou=people,dc=example,dc=com
memberOf: cn=group1,ou=groups,dc=example,dc=com
memberOf: cn=group2,ou=groups,dc=example,dc=com
memberOf: cn=group3,ou=groups,dc=example,dc=com
```

**Comment by stevekuznetsov** [comment]
I've added a test, which adds `memberof` functionality test to the test suite and also refactors to use the LDAP client tools now that they're on the CI server. For whatever reason, though, it's massively flakey and even though there is a connectivity test, the actual tests fail to connect frequently. Need help understanding why.

**Comment by stevekuznetsov** [comment]
@deads2k @bparees I'm seeing `ldapsearch: command not found` on the test, but after https://github.com/openshift/vagrant-openshift/pull/336 we should see the tools on this server. Have we not rolled out a new build?

**Comment by deads2k** [comment]
squash

**Comment by deads2k** [comment]
and figure out why your test fails.

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
Removed test for now, added it to https://github.com/openshift/openldap/pull/12

**Pull request merged**
