### PR TITLE
added test schema

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@deads2k @liggitt This adds a `testPerson` `objectClass` that we can stuff arbitrary attributes into as we see fit. 

The only issue with this implementation is that we need to get an OID. We should be able to subclass from an OID given to RedHat previously, however. If that's not possible, we _could_ stomp on someone else's namespace, but that's bad form. Unfortunately as we need to be root to add schemas, this needs to happen at the image level and we cannot isolate this to happening in our test build.

### CODE REVIEW

**Comment by deads2k** [comment]
For testing, I'm fine with stomping.  Most specs reserve some names for internal use though.

**Comment by deads2k** [comment]
Works for me.  Remove the new test that is relying on functionality we don't seem to have in the image.  This blocks https://github.com/openshift/origin/pull/4972

**Comment by stevekuznetsov** [comment]
@deads2k Removed test, rebased.

**Comment by deads2k** [comment]
lgtm, works locally.

**Pull request merged**
